-- Add migration script here
ALTER TABLE Users
ALTER COLUMN chat_id SET NOT NULL,
ALTER COLUMN age SET NOT NULL,
ALTER COLUMN gender SET NOT NULL,
ALTER COLUMN city SET NOT NULL,
ALTER COLUMN name SET NOT NULL,
ALTER COLUMN telegram_name SET NOT NULL,
ALTER COLUMN about SET NOT NULL,
ALTER COLUMN interested_min_age SET NOT NULL,
ALTER COLUMN interested_max_age SET NOT NULL,
ALTER COLUMN interested_gender SET NOT NULL;

ALTER TABLE Duplets
ALTER COLUMN id SET NOT NULL,
ALTER COLUMN first_user_id SET NOT NULL,
ALTER COLUMN first_user_react SET NOT NULL,
ALTER COLUMN second_user_id SET NOT NULL,
ALTER COLUMN second_user_react SET NOT NULL,
ALTER COLUMN status SET NOT NULL;
